stages:
  - init
  - build
  - test

build:
  stage: init
  script: 
  - ls 

pyth_build:
  image: "python:3.6"
  stage: build
  services:
  - mongo:4.0
  variables:
    MONGO_URI: 'mongodb://mongo/news'
  script:
  - ls
  - pip3 install -r requirements.txt
  - cd Back
  - pip3 install sqlparse==0.2.4
  - python3 manage.py makemigrations news
  - python3 manage.py migrate news
  #- python3 manage.py runserver


vue_build:
  image: node:8
  stage: build
  script: 
  - ls 
  - cd App
  - npm install
  - npm run build 

pyth_test:
    image: "python:3.6"
    stage: test
    script:
    - pip3 install -r requirements.txt
    - cd Back
    - cd Tests 
    - python3 back_tests.py
    - python3 GetNewsFeedTest.py
    
vue_test:
    image: node:8
    stage: test
    script:
    - ls
    - cd App
    - npm install
    - npm run test
  

  